version: 0.2

env:
  variables:
    AWS_REGION: us-east-1

phases:
  pre_build:
    commands:
      - echo "=== pre_build ==="
      - cd $CODEBUILD_SRC_DIR/clinic-crm && npm ci --quiet

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/clinic-crm && npm run build

  post_build:
    commands:
      - echo "=== done ==="

artifacts:
  files:
    - clinic-crm/out/**/*
  base-directory: $CODEBUILD_SRC_DIR
  discard-paths: no

cache:
  paths:
    - clinic-crm/node_modules/**/*
