import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "bg-elevated": "var(--bg-elevated)",
        "bg-soft": "var(--bg-soft)",
        ink: "var(--ink)",
        "ink-soft": "var(--ink-soft)",
        "ink-muted": "var(--ink-muted)",
        line: "var(--line)",
        "line-soft": "var(--line-soft)",
        sky: "var(--sky)",
        "sky-soft": "var(--sky-soft)",
        sage: "var(--sage)",
        "sage-soft": "var(--sage-soft)",
        beige: "var(--beige)",
        "beige-soft": "var(--beige-soft)",
        lavender: "var(--lavender)",
        "lavender-soft": "var(--lavender-soft)",
        rose: "var(--rose)",
        "rose-soft": "var(--rose-soft)",
        accent: "var(--accent)",
        "accent-soft": "var(--accent-soft)",

        // New design system tokens (Figma "landing" file) — additive.
        // Intended for landing/booking work only; dashboard keeps using the tokens above.
        primary: {
          50: "var(--primary-50)",
          100: "var(--primary-100)",
          200: "var(--primary-200)",
          300: "var(--primary-300)",
          400: "var(--primary-400)",
          500: "var(--primary-500)",
          600: "var(--primary-600)",
          700: "var(--primary-700)",
          800: "var(--primary-800)",
          900: "var(--primary-900)",
          DEFAULT: "var(--primary-500)",
        },
        secondary: {
          50: "var(--secondary-50)",
          100: "var(--secondary-100)",
          200: "var(--secondary-200)",
          300: "var(--secondary-300)",
          400: "var(--secondary-400)",
          500: "var(--secondary-500)",
          600: "var(--secondary-600)",
          700: "var(--secondary-700)",
          800: "var(--secondary-800)",
          900: "var(--secondary-900)",
          DEFAULT: "var(--secondary-500)",
        },
        neutral: {
          50: "var(--neutral-50)",
          100: "var(--neutral-100)",
          200: "var(--neutral-200)",
          300: "var(--neutral-300)",
          400: "var(--neutral-400)",
          500: "var(--neutral-500)",
          600: "var(--neutral-600)",
          700: "var(--neutral-700)",
          800: "var(--neutral-800)",
          900: "var(--neutral-900)",
          DEFAULT: "var(--neutral-500)",
        },
        red: {
          50: "var(--red-50)",
          100: "var(--red-100)",
          200: "var(--red-200)",
          300: "var(--red-300)",
          400: "var(--red-400)",
          500: "var(--red-500)",
          600: "var(--red-600)",
          700: "var(--red-700)",
          800: "var(--red-800)",
          900: "var(--red-900)",
          DEFAULT: "var(--red-500)",
        },
        success: {
          50: "var(--success-50)",
          100: "var(--success-100)",
          200: "var(--success-200)",
          300: "var(--success-300)",
          400: "var(--success-400)",
          500: "var(--success-500)",
          600: "var(--success-600)",
          700: "var(--success-700)",
          800: "var(--success-800)",
          900: "var(--success-900)",
          DEFAULT: "var(--success-500)",
        },
        warning: {
          50: "var(--warning-50)",
          100: "var(--warning-100)",
          200: "var(--warning-200)",
          300: "var(--warning-300)",
          400: "var(--warning-400)",
          500: "var(--warning-500)",
          600: "var(--warning-600)",
          700: "var(--warning-700)",
          800: "var(--warning-800)",
          900: "var(--warning-900)",
          DEFAULT: "var(--warning-500)",
        },
      },
      borderRadius: {
        sm: "10px",
        DEFAULT: "16px",
        lg: "22px",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(16, 24, 52, 0.04)",
        DEFAULT: "0 2px 8px rgba(16, 24, 52, 0.05), 0 1px 2px rgba(16, 24, 52, 0.04)",
        lg: "0 12px 40px rgba(16, 24, 52, 0.10), 0 2px 8px rgba(16, 24, 52, 0.05)",
      },
      fontFamily: {
        vazir: ["Vazirmatn", "system-ui", "sans-serif"],
        estedad: ["Estedad", "system-ui", "sans-serif"],
      },
      // New type scale sampled from the Figma "Typography - vazirmatn" specimen — additive.
      // Existing default Tailwind text-* utilities (used throughout the dashboard) are untouched.
      fontSize: {
        tiny: ["10px", { lineHeight: "16px", letterSpacing: "0.3px" }],
        small: ["12px", { lineHeight: "18px", letterSpacing: "0.2px" }],
        caption: ["14px", { lineHeight: "22px", letterSpacing: "0.2px" }],
        body: ["16px", { lineHeight: "20px", letterSpacing: "0.2px" }],
        h6: ["20px", { lineHeight: "24px" }],
        h5: ["24px", { lineHeight: "28px" }],
        h4: ["30px", { lineHeight: "34px" }],
        h3: ["40px", { lineHeight: "44px" }],
        h2: ["60px", { lineHeight: "60px" }],
        h1: ["80px", { lineHeight: "80px" }],
      },
    },
  },
  plugins: [],
};

export default config;
